name: calorie_wise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc_test: ^10.0.0
  camera: ^0.11.0+1
  camera_android_camerax: ^0.6.5
  cloud_firestore: ^6.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  intl: ^0.20.2
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Avatar.png
    - assets/icon1.png
    - assets/000.jpg
    - .env
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon1.png"
